### ISSUE TITLE
Preview font?

### ISSUE THREAD

**Issue by yaoberh** [AustinHasten/AnkiRandomFont#1]
Hey!
Was wondering if it's possible to preview the font one wants to add or remove from a specific language list.
This would be especially useful for languages like japanese or chinese where some fonts are calligraphic and others more for daily reading.

**Comment by AustinHasten** [comment]
I like the idea, I'll look into it.

**Comment by AustinHasten** [comment]
@yaoberh Try out the below version and let me know what you think.
[RandomFont.zip](https://github.com/AustinHasten/AnkiRandomFont/files/6742294/RandomFont.zip)

**Comment by yaoberh** [comment]
So cool! Working perfectly. Thanks so much :1st_place_medal:
