### ISSUE TITLE
Malgun Gothic is not Chinese

### ISSUE THREAD

**Issue by khonkhortisan** [AustinHasten/AnkiRandomFont#2]
For SimplifiedChinese/TraditionalChinese, disable Malgun Gothic/Malgun Gothic Semilight. It's a Korean font that only has some of the characters, so for the sentence 你为什么那么做？, \_\_什_那_做？ shows as thick sans and 你为_么_么_ shows as thin serif. 
You can test which characters it supports here https://catalog.monotype.com/family/microsoft-corporation/malgun-gothic
This can be done through the addon settings, but having it disabled/removed by default saves having to track it down with AnkiWebView Inspector.
![imagen](https://user-images.githubusercontent.com/1996449/127068482-92cfdb73-c40e-42c7-b273-b81532450532.png)

**Comment by AustinHasten** [comment]
I don't determine what writing systems a font supports, Qt does. Maybe I could add a tool tip somewhere to let you know what font was currently being used to help troubleshoot things like this, but I can't change the way Qt decides what fonts support what writing systems.

**Comment by khonkhortisan** [comment]
[crosslinking https://bugreports.qt.io/browse/QTBUG-95402]
