### ISSUE TITLE
Error loading in 2.1.53

### ISSUE THREAD

**Issue by jperaita** [AustinHasten/AnkiRandomFont#6]
Hi,

I get the following error message when starting 2.1.53 after install of the add-on:
- - - 
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Randomize Fonts':
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\perai\AppData\Roaming\Anki2\addons21\1603486068\__init__.py", line 187, in <module>
    allInstalledFonts = QFontDatabase().families()
TypeError: QFontDatabase(QFontDatabase): not enough arguments
- - -

Any idea?

Thanks.

_Edited_: Fixed hideous formatting

**Comment by yaoberh** [comment]
Same!

**Comment by CodeYan01** [comment]
This also happened to me on 2.1.55

**Comment by CodeYan01** [comment]
This is likely because of the Qt6 update. I fixed the script by changing `QFontDatabase()` to just `QFontDatabase`. I also removed the `from PyQt5.QtCore import *` as it is not necessary

**Comment by AustinHasten** [comment]
You got it
